[technote]
id = "SITCOMTN-100"
series_id = "SITCOMTN"
canonical_url = "https://sitcomtn-100.lsst.io"
github_url = "https://github.com/lsst-sitcom/sitcomtn-100"
github_default_branch = "main"
date_created = 2023-12-11T13:04:33Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Merlin"
name.family = "Fisher-Levine"
orcid = "https://orcid.org/0000-0001-9440-8960"
internal_id = "fisherlevinem"
[[technote.authors.affiliations]]
name = "Rubin Observatory Project Office"
internal_id = "RubinObs"
address = "950 N. Cherry Ave., Tucson, AZ  85719, USA"
